version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Build started"
      - echo "No build required for static website"
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
